import Head from 'next/head'
import Login from './login'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Eat Smart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/login">login</Link>
      <Link href="/register">signup</Link>
      <Link href="/bmi">guest</Link>
      
    </>
  )
}
